### ISSUE TITLE
gamemode creative does not take effects

### ISSUE THREAD

**Issue by rezagh** [itzg/minecraft-server-charts#106]
in the latest chart v 3.8.0 that uses latest image `Image:      itzg/minecraft-server:latest`, I can see `MODE:                          CREATIVE` but it doesn't take effect. When i connect to the world it is survival.

Any idea?

**Comment by itzg** [comment]
After first startup you will need to set `overrideServerProperties=true`

**Comment by rezagh** [comment]
thanks
