### ISSUE TITLE
Minecraft server chart doesn't set FTP_MODPACK_ID

### ISSUE THREAD

**Issue by evilhamsterman** [itzg/minecraft-server-charts#118]
When trying to use the Minecraft chart with the type set to FTBA there is no place to set the FTB_MODPACK_ID which caused the container to fail with
```
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx 2 0 0 4096 Mar 21 22:02 /data'
[init] Resolved version given LATEST into 1.18.2 and major version 1.18
[init] Resolving type given FTBA
[init] ERROR FTB_MODPACK_ID is required with TYPE=FTB
```
There is an option for minecraftServer.ftbServerMod but that doesn't set the FTB_MODPACK_ID environment variable. You can set the variable in the extraEnv section and everything works fine, but it isn't obvious.

**Comment by itzg** [comment]
Thanks. I'll get that changed queued up, but would also be happy to accept a PR for that.
