### ISSUE TITLE
Stupid Question: How do you configure spigot plugins when using this chart?

### ISSUE THREAD

**Issue by illegitimate-egg** [itzg/minecraft-server-charts#126]
In the description of the chart on artifact hub it says that:
> The `itzg/minecraft` image stores the saved games and mods under /data.

This confused me because I didn't even know that kubernetes had writable directories inside containers.

How would I go about accessing data to configure mods?

**Comment by itzg** [comment]
> This confused me because I didn't even know that kubernetes had writable directories inside containers.

Yep, any volume can be mounted read/write when it makes sense. 

As for how to access the data, it will vary based upon [the volume type](https://kubernetes.io/docs/concepts/storage/volumes/#volume-types) you use. In general though, you can `kubectl exec` into the pod's minecraft server container and use the pre-installed [nano text editor](https://www.nano-editor.org/) to make text changes.

Here's some more background on the `/data` mount point of the minecraft image:

https://github.com/itzg/docker-minecraft-server#data-directory

**Comment by illegitimate-egg** [comment]
That interesting, because when I tried to use cp to copy a plug in over to `/data/bukkit`, I got told that it was a read-only filesystem, even when I later tried wget using exec!

**Comment by illegitimate-egg** [comment]
> As for how to access the data, it will vary based upon [the volume type](https://kubernetes.io/docs/concepts/storage/volumes/#volume-types) you use.
You can select a volume type? I was just running this bear on a raspberry pi cluster

**Comment by itzg** [comment]
I believe the default is emptyDir, which is basically a managed host directory similar to what Docker does by default with volumes.

**Comment by illegitimate-egg** [comment]
oh ok
