### ISSUE TITLE
Default version update?

### ISSUE THREAD

**Issue by TJM** [itzg/minecraft-server-charts#13]
I petition that we should release a new chart version with an updated app version 1.16.1 is out, and we are still defaulting to 1.14.4. I am happy to submit a PR, but before I do, I wanted to see if there was some reason why we were still defaulting to 1.14.4.

**Comment by billimek** [comment]
I agree, I suspect @itzg would agree too.  If you could submit a PR for this, it would be great!

**Comment by itzg** [comment]
Yep, I asked @billimek to change that in the bedrock chart while on there the other day. I agree a PR would be great with that defaulting to "LATEST".
