### ISSUE TITLE
rcon daemon is not started altough enabled

### ISSUE THREAD

**Issue by baflo** [itzg/minecraft-server-charts#134]
Hey,

I am currently trying to set up these charts, but currently I am struggling with RCON. I have enabled it in the minecraft-server-chart, but it does not seem to start. I cannot use `rcon-cli` inside the container. It seems no other service but minecraft server is started.

```
[fb@server-nuc ~]$ k -n minecraft exec -ti deploy/minecraft-minecraft -- bash
groups: cannot find name for group ID 2000
minecraft@minecraft-minecraft-595b6b75bd-26l2z:~$ env | grep -i rcon
MINECRAFT_MINECRAFT_RCON_PORT=tcp://10.43.116.247:25575
RCON_PASSWORD=D3/|C9jQq?d%c\m$2bk8O1zG$bKZ3U.N
MINECRAFT_MINECRAFT_RCON_PORT_25575_TCP_ADDR=10.43.116.247
MINECRAFT_MINECRAFT_RCON_PORT_25575_TCP_PROTO=tcp
MINECRAFT_MINECRAFT_RCON_PORT_25575_TCP=tcp://10.43.116.247:25575
MINECRAFT_MINECRAFT_RCON_SERVICE_HOST=10.43.116.247
ENABLE_RCON=true
MINECRAFT_MINECRAFT_RCON_SERVICE_PORT=25575
MINECRAFT_MINECRAFT_RCON_SERVICE_PORT_RCON=25575
MINECRAFT_MINECRAFT_RCON_PORT_25575_TCP_PORT=25575
minecraft@minecraft-minecraft-595b6b75bd-26l2z:~$ netstat -tulpn
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp6       0      0 :::25565                :::*                    LISTEN      275/java
minecraft@minecraft-minecraft-595b6b75bd-26l2z:~$ rcon-cli
2022/10/04 20:33:57 Failed to connect to RCON serverdial tcp [::1]:25575: connect: connection refused
minecraft@minecraft-minecraft-595b6b75bd-26l2z:~$
```

minecraft-chart-version: 4.3.0
rcon-chart-version: 1.0.0

**Comment by itzg** [comment]
Rcon is not a separate daemon -- it's part of the Minecraft server itself. Please provide your helm values since the address it's trying to access seems to be wrong.

**Comment by baflo** [comment]
Thanks for the quick response :D 

Here are the Helm values for 

```
[fb@server-nuc ~]$ helm -n minecraft list
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
minecraft       minecraft       3               2022-10-04 19:24:55.571605314 +0000 UTC deployed        minecraft-4.3.0         SeeValues
rcon-web-admin  minecraft       1               2022-10-04 20:29:32.363726066 +0000 UTC deployed        rcon-web-admin-1.0.0    0.14.1-1
```

**minecraft**
[fb@server-nuc ~]$ helm -n minecraft get values minecraft
USER-SUPPLIED VALUES:
ingress:
  enabled: true
  hosts:
  - name: minecraft.anpingen.de
minecraftServer:
  eula: true
  rcon:
    enabled: true
    password: ******1
persistence:
  dataDir:
    enabled: true
startupProbe:
  enabled: true
```

**rcon-web-admin**

```
[fb@server-nuc ~]$ helm -n minecraft get values rcon-web-admin
USER-SUPPLIED VALUES:
ingress:
  enabled: true
  host: minecraft-rcon.anpingen.de
rconWeb:
  password: ******2
  rconHost: minecraft-minecraft
  rconPassword: ******1
```

**Comment by baflo** [comment]
Thanks for the quick response :D 

Here are the Helm values for 

```
[fb@server-nuc ~]$ helm -n minecraft list
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
minecraft       minecraft       3               2022-10-04 19:24:55.571605314 +0000 UTC deployed        minecraft-4.3.0         SeeValues
rcon-web-admin  minecraft       1               2022-10-04 20:29:32.363726066 +0000 UTC deployed        rcon-web-admin-1.0.0    0.14.1-1
```

**minecraft**

```
[fb@server-nuc ~]$ helm -n minecraft get values minecraft
USER-SUPPLIED VALUES:
ingress:
  enabled: true
  hosts:
  - name: minecraft.example.com
minecraftServer:
  eula: true
  rcon:
    enabled: true
    password: ******1
persistence:
  dataDir:
    enabled: true
startupProbe:
  enabled: true
```

**rcon-web-admin**

```
[fb@server-nuc ~]$ helm -n minecraft get values rcon-web-admin
USER-SUPPLIED VALUES:
ingress:
  enabled: true
  host: minecraft-rcon.example.com
rconWeb:
  password: ******2
  rconHost: minecraft-minecraft
  rconPassword: ******1
```

**Comment by itzg** [comment]
That's strange since all your configs look right. Thanks for the netstat, which confirms it's not properly listening on 25575 for some reason. Can you grep out the "rcon" properties in `server.properties`?

**Comment by itzg** [comment]
...you might need to set `minecraftServer.overrideServerProperties=true` if the rcon settings where not originally there.

**Comment by baflo** [comment]
```
minecraft@minecraft-minecraft-595b6b75bd-26l2z:~$ grep rcon server.properties
rcon.port=25575
broadcast-rcon-to-ops=true
enable-rcon=false
rcon.password=minecraft
```

**Comment by baflo** [comment]
@itzg It actually helped to set `minecraftServer.overrideServerProperties=true`. The RCON service runs, now. Thank you a lot.

>  \# By default, the server configuration will be created and set based on the following environment variables, but only the first time the server is started
>  \# If you would like to override the server configuration each time the container starts up, you can set this to true
>  \# see https://github.com/itzg/docker-minecraft-server#server-configuration
>  overrideServerProperties: false

What consequences are implied, if I leave it permanently?

**Comment by baflo** [comment]
@itzg The service is available, however now I have authentication issues:

```
minecraft@minecraft-minecraft-677fb8f55f-dbpvg:~$ rcon-cli --password $RCON_PASSWORD
2022/10/05 15:04:59 Failed to connect to RCON serverrcon: authentication failed
```

**Comment by baflo** [comment]
nvm, the RCON service apparently didn't like my special symbols. With a all-hex password it works like a charm. Also, I got rcon-web-admin connected 👍

**Comment by baflo** [comment]
nvm, the RCON service apparently didn't like my special symbols. With a all-hex password it works like a charm. Also, I got rcon-web-admin connected 👍

**Comment by itzg** [comment]
> What consequences are implied, if I leave it permanently?

None. In fact, I'm should make that the default.
