### ISSUE TITLE
Minecraft server envMap values that default to true can't be made false

### ISSUE THREAD

**Issue by ClashTheBunny** [itzg/minecraft-server-charts#153]
In this line of the envMap snippet, you can see that if a value, like onlineMode, is set to false, it won't even include the variable.  The problem is that if ONLINE_MODE defaults to true, it's absense will make it true, even though it's set to false in the helm chart values.

The fix would be to remove the if and always include a variable or you could default everything to false in the minecraft container.  I think you would have a big support problem if you defaulted everything to false, so I'd assume you want to just remove the if statement here and always set an env variable.

https://github.com/itzg/minecraft-server-charts/compare/minecraft-4.5.0...minecraft-4.7.4#diff-6388d0bd6acdc6fb5c4741f9392e7f16a04efd7dcd4ebde73fe24af5db7e4c00R29

**Comment by ChipWolf** [comment]
Maybe there's a CI thing we can do here to pull the tagged image down if it's changed in values & update the deployment; or just completely delegate configuration to the image instead of duplicating efforts here

**Comment by itzg** [comment]
> just completely delegate configuration to the image instead of duplicating efforts here

That's exactly what I've been trying to push for. 

In any case, PRs are very welcome @ClashTheBunny 😀

**Comment by itzg** [comment]
...in the meantime I'll revert that commit. That was just me trying make helm less annoying.

**Comment by ClashTheBunny** [comment]
I really like the way you did it, but I do appreciate the revert until it can solve this edge case!

**Comment by ChipWolf** [comment]
> That's exactly what I've been trying to push for. 

Without a major version bump on the chart, the only way I can conceive of deprecating `.Values.minecraftServer` predictably would be to:
- throw the envMap back in with the chart defaults, but prefix the target names they're rendered to with something like `MIGRATE_`.
- add an `initContainer` that compares the [default] variables set in the tagged server container
  - weaves in the delta between the two, sets of variables
  - optionally throw a depreciation warning up in the console (perhaps include a a reformatted Helm `values.yaml` for ease of migration to the next major chart version)

Tag a major version after this, rip all the complexity out of the chart, winner winner 🍗

**Comment by ChipWolf** [comment]
If we can get itzg/docker-minecraft-server#1439 somewhere, it would be a neat way to avoid things like this.

Akin to API versions, the config structure could contain the schema version and could be transformed between versions in a more consistent way.

**Comment by itzg** [comment]
@billimek @gtaylor can one of you step in here and take over? I don't have the time or mental energy to maintain these charts anymore.

**Comment by gtaylor** [comment]
Hey @itzg, I don't think I'm interested in maintaining these anymore. It may be time to mark these as archived and move on to other things.

Thanks for carrying them forward as long and well as you did!

**Comment by itzg** [comment]
I had an epiphany: in PR #157 I am introducing the concept of a "default" value for the boolean fields. When those fields are "default", they will be left out of the rendered manifest. When the usual `true` or `false`, they will be included.
