### ISSUE TITLE
How to configure velocity

### ISSUE THREAD

**Issue by arno4000** [itzg/minecraft-server-charts#165]
According to https://github.com/itzg/minecraft-server-charts/blob/master/charts/minecraft-proxy/values.yaml#L127 the minecraft-proxy chart currently only supports config files, which are yaml. But velocity uses toml for its config file and velocity is supported by the chart. 

So my question is, how can I specify the config for velocity in the values.yaml of the minecraft-proxy chart?

**Comment by itzg** [comment]
Yeah it seems to do extraneous processing to take the text block and turn it into yaml

https://github.com/itzg/minecraft-server-charts/blob/2406a8c2c6c075cf11bde390e8ac8ea006b49e4a/charts/minecraft-proxy/templates/configmap.yaml#L12

Removing the toYaml would probably fix it. 

Since I'm not personally working on this repo anymore, then a PR would be great.

**Comment by arno4000** [comment]
It actually seems that the toYaml is not the problem. Instead, the `itzg/bungeecord` image seems to have a bug when mounting the `velocity.toml` to /server. I created a issue for this problem at https://github.com/itzg/docker-bungeecord/issues/133.

**Comment by skylerspaeth** [comment]
I know this is an old issue, but in case it helps anyone else in the future, thanks to @ChipWolf's comment [here](https://github.com/itzg/minecraft-server-charts/pull/65#discussion_r608180401), I was able to configure velocity through the chart's `values.yaml`.

> ```yaml
> configFilePath: /server/velocity.toml
> config: |-
>  config-version = "1.0"
>  bind = "0.0.0.0:25577"
>  motd = "Look PR 65 - it works!"
>  show-max-players = 500
>  ...
> ```

And for what it's worth, I'm hoping to get [this PR ](https://github.com/itzg/minecraft-server-charts/pull/236)merged to add a comment with this example to the `values.yaml` (in addition to Velocity forwarding secret support).
