### ISSUE TITLE
Proxy tty/stdin not working with Helm chart

### ISSUE THREAD

**Issue by AeonRemnant** [itzg/minecraft-server-charts#175]
Pretty much exactly what is says. 
I'm playing around testing some new software and using the standard minecraft-proxy helm chart doesn't allow me to kubectl attach to it, which is fine because it doesn't come shipped with tty and stdin out of the box, but I can't figure out where exactly these should go since the chart is a little confusing. Helm says it goes in spec and there is no spec in this chart. 

Still new here so I'm a smidge confused.

I'm pretty sure my config is borked but just to be sure and sanity check I'll poke in here since I can see there's docker compose config with tty and stdin in the docs so I'm certain it's allowed by default.

**Comment by itzg** [comment]
Making a note that the deployment template for the proxy needs similar to

https://github.com/itzg/minecraft-server-charts/blob/2b64e8212444956bc3531e8422d462bbe0238e7a/charts/minecraft/templates/deployment.yaml#L155

**Comment by itzg** [comment]
No, the chart itself needs to be modified. 

(Personally I don't use Helm because I prefer the flexibility to modify the manifests directly.)

**Comment by itzg** [comment]
To phrase the answer differently: you could clone this repo, change the charts deployment file manually, and that'll work. At that point a PR to submit back that change would be awesome 😀

**Comment by AeonRemnant** [comment]
I'm eyeballing manifests, yeah. Trying to poke into GitOps but I don't expect to be full ball on it for a good while. :p
Yeah I'll poke around and go do some testing.

**Comment by itzg** [comment]
I totally get that. It'll be an easy change for me -- just need to spin off a few minutes to do it 😁.

**Comment by AeonRemnant** [comment]
I mean hey, may as well learn as much as I can, y'know? 
Kube isn't even remotely kind if you're unwilling to dig into things and tinker.

**Comment by itzg** [comment]
Just wanted to point out that chart version 3.3.1 now enabled tty and stdin.

**Comment by AeonRemnant** [comment]
Tried and tested, works perfectly. :)
I appreciate it, mate.
