### ISSUE TITLE
How do you obtain an external IP address after installing?

### ISSUE THREAD

**Issue by PunkmeisterDuy** [itzg/minecraft-server-charts#18]
Sorry I tried following the instructions of:

```
Get the IP address of your Minecraft server by running these commands in the
same shell:
  export POD_NAME=$(kubectl get pods \
    --namespace minecraft \
    -l "component=minecraft-minecraft" \
    -o jsonpath="{.items[0].metadata.name}")
  kubectl port-forward $POD_NAME 25565:25565
  echo "Point your Minecraft client at 127.0.0.1:22565"
```

when trying to do the first command I get an error:
```
error: error executing jsonpath "{.items[0].metadata.name}": Error executing template: array index out of bounds: index 0, length 0. Printing more information for debugging the template:
        template was:
                {.items[0].metadata.name}
        object given to jsonpath engine was:
                map[string]interface {}{"apiVersion":"v1", "items":[]interface {}{}, "kind":"List", "metadata":map[string]interface {}{"resourceVersion":"", "selfLink":""}}
```

Sorry I am new to kubernetes and Bash, but for the "export POD_NAME" do we replace the POD_NAME with the pod name from:

```
kubectl get pods -n minecraft

minecraft-minecraft-668c498d5b-59n6d
```

I tried replacing the POD Name from what I got from the namespace, but got:
`bash: export: `minecraft-minecraft-668c498d5b-59n6d=': not a valid identifier`

I am executing helm from my computer and not on the kubernetes master. The cluster is a raspberry pi cluster

**Comment by itzg** [comment]
You're on the right path with the `kubectl get pods -n minecraft` approach. With that pod name as an example, the command you want to run is

```
kubectl port-forward minecraft-minecraft-668c498d5b-59n6d 25565:25565
```

However, if you don't plan on putting a proxy in front of the server, I would recommend setting the helm value `minecraftServer.serviceType` to "NodePort". It'll initially pick a random binding port across the nodes, but at least you won't have to keep the port-forwarding running always.

**Comment by PunkmeisterDuy** [comment]
Thank you very much, I set the service type to NodePort and was able to connect to the server. However, when I did:

`kubectl get svc -n minecraft`

I still did not get an external IP address. I connected by just putting the IP of any of my nodes to connect. Do you know why kubectl won't display the external address.

```
---
minecraftServer:
  serviceType: "NodePort"
  loadBalancerIP: 192.168.1.199 
```

I also have a question about the loadBalancerIP, I just put the IP of my master node, I am not sure how that works.

Thank you very much for your time.

**Comment by itzg** [comment]
Those instructions are a bit misleading. Both NodePort and the default ClusterIP types have no control over your external/public facing networking configuration. You'll need to setup port forwarding manually towards the NodePort you found with `kubectl get svc`.

If you're using a public cloud managed kubernetes cluster, like GKE or EKS, then you can use `serviceType: LoadBalancer` and let the kubernetes cluster setup a public facing load balancer with a true external IP address. (Keep in mind that managed load balancers incur extra charges for the load balancer itself and the public IP address.)

**Comment by itzg** [comment]
...as an example of the manual port forwarding, my deployment allocated a node port of 31005, so I went into my router and setup a public internet facing port forwarding rule:

![image](https://user-images.githubusercontent.com/988985/95000500-ec1cd080-0586-11eb-822d-508c56911a65.png)

**Comment by nevets963** [comment]
@itzg In a post above, you suggested to use a proxy in front of the server. Do you have an example of this, or which proxy one would use?

**Comment by itzg** [comment]
@nevets963 I implemented and use this to do simple multiplexing of the minecraft port onto several minecraft server pods by hostname:

https://github.com/itzg/mc-router

BungeeCord and derivatives are the other proxies I know about.

**Comment by nevets963** [comment]
Ah, nice! Thanks for sharing
