### ISSUE TITLE
'vanillaTweaksShareCodes' in 'minecraft' chart not working as expected

### ISSUE THREAD

**Issue by llajas** [itzg/minecraft-server-charts#181]
Hello!

I'm trying to use the `vanillaTweaksShareCodes` option that comes with the java 'Minecraft' chart to have a VanillaTweaks resource pack loaded into the server directly. The world starts successfully, and I can join the world but I don't see any resources in Resource Packs on my client when I open the game menu and browse to it.

Closer look at the logs does reveal that the code I'm passing (`Vegtun` which is from 'https://vanillatweaks.net/share#Vegtun') is being interpreted and downloaded.

```sh
[mc-image-helper] 08:45:00.785 INFO  : Downloading Vanilla Tweaks resourcepacks for share code Vegtun
```

Furthermore, I can exec into the pod for the server and I do see a 'resourcepacks' folder with the .zip file inside (VanillaTweaks_5c1c124.zip), but I'm confused as to how to get it to load into the server. I also set `resourcePackEnforce` to 'true' but I never receive a prompt from the server to load them into my client. For good measure, I did a SHA-1 checksum on the .zip file and included that as the value for `resourcePackSha` but that didn't change anything either.

The same .zip file works if I import it locally to the client I'm playing from, but I would like to have it server side, if at all possible.

Please let me know if further information is needed or if I'm just missing something very simple. Thanks a ton for this helm chart among others!

**Comment by itzg** [comment]
Unfortunately it turns out resource packs via vanilla tweaks aren't actually usable -- I really need to remove support and log with an error in the image startup. The reason is that the server property is intended to be a URL that the clients can access, so downloading the resource pack to the server's filesystem is not beneficial in the end.

**Comment by llajas** [comment]
Makes sense. Thanks for the fast reply on this one. I'll go ahead and switch to delivering those resources using an external server, I'm just glad to know I wasn't doing something wrong there.

I'll go ahead and close this. Thanks again for your work here!
