### ISSUE TITLE
Minecraft Server Type: Fabric

### ISSUE THREAD

**Issue by Hazerre** [itzg/minecraft-server-charts#194]
Please include a way to use Fabric as the server type. Example for download link is below:

https://fabricmc.net/use/server/

**Comment by itzg** [comment]
That has been supported for a while

https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/server-types/fabric/

**Comment by itzg** [comment]
Apparently the comment in the values needs to be updated to simply point at the docs
