### ISSUE TITLE
Upgraded to 2.8.1 and now server cannot start (permission denied)

### ISSUE THREAD

**Issue by osirisguitar** [itzg/minecraft-server-charts#239]
I upgraded from 2.0.0 to 2.8.1 for the fix where the pod could not download the latest server. Download now works fine, but startup fails with:

```
Downloading Bedrock server version 1.21.43.01 ...
Backing up behavior_packs into backup-pre-1.21.43.01
mv: cannot move 'behavior_packs' to 'backup-pre-1.21.43.01/behavior_packs': Permission denied
```

**Comment by itzg** [comment]
Check the files and directories ownership with `ls -n`. The server software runs as UID 1000 by default.

**Comment by osirisguitar** [comment]
Thanks! All of the files had suddenly had owner changed to 0.

(for anyone running k3s, you can change file ownership on the host in the mapped pvc directory, even if the pod itself can't start).
