### ISSUE TITLE
Minecraft Server defaults to offline mode

### ISSUE THREAD

**Issue by caycehouse** [itzg/minecraft-server-charts#245]
After upgrading my Minecraft servers from chart version 4.23.3 to 4.23.4, they now default to offline mode. I have overrideServerProperties set to true, but I didn't explicitly set onlineMode, which previously defaulted to true. Is this an unintended change, or do I now need to set onlineMode: true explicitly? This seems related to #241.

**Comment by itzg** [comment]
No, that's not intended. You're probably right that it's related to that PR. 

Can you provide the full set of values you're using? Also providing debug/dryrun output of chart upgrade would help.

**Comment by itzg** [comment]
Oh I see now, it didn't take into account the special value "default" to indicate that the Minecraft default should be left as is.

**Comment by itzg** [comment]
New chart 4.23.6 is now released
