### ISSUE TITLE
Consider using ingress

### ISSUE THREAD

**Issue by louis030195** [itzg/minecraft-server-charts#31]
In the use case where we want to expose the server to the public, I think [Kubernetes Ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/) would be better than exposing the service as NodePort, for domain name, pathes etc .. ?

**Comment by billimek** [comment]
Most ingress controllers only support http protocol and Minecraft is a dedicated protocol requiring generic TCP. 

Because of this, sadly, most ingress approaches would not work.

**Comment by itzg** [comment]
Agreed with @billimek . nginx ingress has some non-standard options for bare TCP ingress; however, even then it won't help much since it's not aware of the server selection in the proprietary Minecraft handshake packet. 

I implemented and use https://github.com/itzg/mc-router as my compromise for lack of ingress support.

**Comment by jfmatth** [comment]
> In the use case where we want to expose the server to the public, I think [Kubernetes Ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/) would be better than exposing the service as NodePort, for domain name, pathes etc .. ?

You really should use a LoadBalancer for this.  hacking up the ingress isn't the way to go

**Comment by itzg** [comment]
Ah yes, excellent point @jfmatth . Once I saw mention of ingress I was thinking layer-7 routing was part of the use case. 

To be more specific, when I have deployed on GCP or DigitalOcean I'd use mc-router and then a cloud LB in front of that to pay only once for the LB regardless of how many server hostnames were being routed :)

**Comment by louis030195** [comment]
Thanks for the clarification !
