### ISSUE TITLE
Thoughts on restoring worlds?

### ISSUE THREAD

**Issue by jfmatth** [itzg/minecraft-server-charts#32]
Thanks again for this Chart, working great.

The kubectl cp backup example for backing it up, but will the reverse work for a restore?

Thanks

**Comment by billimek** [comment]
@jfmatth I do exactly this with success.  It works ok.  Generally speaking, I `kubectl exec -ti <minecraft pod> -- sh` and then do whatever operation I need with 'local' files in the minecraft filesystem to prep a new or restored world from either a local backup or something I copy in via `kubectl cp ...`.

After staging the new world I kill the pod and the new instance is running the new/restored world depending on the `server.properties` configuration.

**Comment by jfmatth** [comment]
@billimek Thanks for the (super) quick response!

I've used the ```kubectl exec``` method too, but had weird results.  I'm trying the method I'm asking about now, and we'll see what happens.

i hosted on a VM before I'm moving to K8s, crossing my fingers.

Thanks again

**Comment by jfmatth** [comment]
I'm gonna see if i can make a pod that is just for backup and restore, similar to what some other operators do.

thanks again for this repo, works great!
