### ISSUE TITLE
Extra port definitions

### ISSUE THREAD

**Issue by hyperbolic2346** [itzg/minecraft-server-charts#37]
I'm trying to get dynmap to come through with this chart and I'm trying to figure out which way it should be handled. I can see a specific `dynmap: true` flag that does the things or something more generic like `extraPorts` that pastes anything inside into the deployment and service yaml. I can see value in the former because it is easy for people to add dynmap then and the latter because it's easier to select what ports you may need and how to expose them.

Thoughts?

**Comment by itzg** [comment]
Yes, it's hard to decide for the same reasons you gave. I think I'm leaning towards the generic `extraPorts` type approach just in case users come across any other plugins that need others.

**Comment by hyperbolic2346** [comment]
Would you expect these to tag along with the minecraft service as more ports or as services of their own? I originally made this as another port on the service, but I can surely see the desire to keep them separate like the rcon-service.

If we push it to a stand-alone service, it seems more involved than just "we will insert whatever yaml you want into the ports" and more in the realm of "give me a list of ports with defined options and I will build services for you". I'm not sure how far this chart wants to go into yaml config vs options and also just how involved we want this to become.

My immediate desire is to allow dynmap easily in my deployment. I've even toyed with the idea of exposing it via ingress, but that seems overly specific. Maybe dynmap is popular enough that incorporating a dynmap-specific configuration would make sense though?

**Comment by itzg** [comment]
That's a good point about the rcon service being distinct already. Agreed, dynmap does seem to be popular enough to warrant a specific option for it and so far is the only port-exposing plugin I have heard about it. 

Now I'm leaning towards the idea of a dynmap specific option.

**Comment by itzg** [comment]
Fixed in #38
