### ISSUE TITLE
Import data feature

### ISSUE THREAD

**Issue by shokohsc** [itzg/minecraft-server-charts#39]
Hello, thanks for this project.

Quick question: How can I import a backup done with `itzg/mc-backup` ?
I guess one answer would be to fill a PVC, then use it as an existing claim.

I'd like to be able to define an initContainer in your charts so that we can use `itzg/mc-backup` image to GET a backup from wherever, then fill a shared PVC with the main container so that it would start with an eixsting world.

Would that be an interesting feature for your charts ?

I'm thinking about adding an inline initContainer like so: https://github.com/bitnami/charts/blob/master/bitnami/postgresql/templates/statefulset.yaml#L132-L134
&
https://github.com/bitnami/charts/blob/master/bitnami/postgresql/values.yaml#L483-L488

What do you think ?

**Comment by itzg** [comment]
I have only done it with the `WORLD` variable referencing the backup file from an additional volume mount. But yes, an initContainer would make sense. If you could create a PR, let's see how that looks.
