### ISSUE TITLE
rcon error

### ISSUE THREAD

**Issue by neutrongenious** [itzg/minecraft-server-charts#45]
Change values to:
  rcon:
    enabled: TRUE

and try deploying. Kubernetes throws this error

`Error: UPGRADE FAILED: YAML parse error on minecraft/templates/rcon-svc.yaml: error converting YAML to JSON: yaml: line 6: did not find expected key`

**Comment by itzg** [comment]
Sorry, yes, I managed to break that with the most recent PR

https://github.com/itzg/minecraft-server-charts/pull/43

I'll be able to fix that pretty soon/easily.
