### ISSUE TITLE
Add start probe to support lengthy init of modpacks

### ISSUE THREAD

**Issue by itzg** [itzg/minecraft-server-charts#47]
Only thing I would suggest is adding a start probe, some modpacks can take up for 10 mins to boot on init install. 

Thank you!
/close

__Originally posted by @Blackphidora in https://github.com/itzg/minecraft-server-charts/issues/44#issuecomment-765095241__

**Comment by ChipWolf** [comment]
There are https://github.com/itzg/minecraft-server-charts/blob/master/charts/minecraft/values.yaml#L41

Is this issue asking for something else?

**Comment by itzg** [comment]
I even approved/merged the PR that added the startup probes 😬

Thanks as always @ChipWolf , for keeping me honest.
