### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by ChipWolf** [itzg/minecraft-server-charts#49]
Is the lack of license intentional on this repo?

**Comment by billimek** [comment]
I don't think so. @itzg do you mind if I PR a license (thinking apache2)?

**Comment by itzg** [comment]
Oops, not intentional. Yeah, I'll add an apache2 license since that seems to be what I picked for others.

**Comment by itzg** [comment]
Actually MIT will be better since I remember now that it doesn't require sticking copyright header on everything, which I'm missing in my other repos.
