### ISSUE TITLE
Add Bluemap support like Dynmap

### ISSUE THREAD

**Issue by anthr76** [itzg/minecraft-server-charts#53]
Bluemap is like Dynmap and is a new project that seems to be much lighter on the resources. I've been using it for local testing and it's been great. Would a PR be welcomed in the coming weeks to get this added to the chart in the way DynMap is?

**Comment by itzg** [comment]
That sounds great.

**Comment by ChipWolf** [comment]
Technically, the _"dynmap support"_ is just an ancillary service & ingress and would universally work with anything which requires another port.
Just set your `minecraftServer.dynmap.containerPort` and `minecraftServer.dynmap.service.port` values from the default 8123 to 8100.

**Comment by anthr76** [comment]
Right, would it make sense to just do some clever renamings?

**Comment by ChipWolf** [comment]
> 
> 
> Right, would it make sense to just do some clever renamings?

Yeah, I'm sure we could essentially just find and replace the word `dynmap` with something a little more generic. It doesn't affect functionality for now though.

**Comment by itzg** [comment]
Hey @hyperbolic2346, I just remembered we pondered in #37 whether we should go generic or dynmap specific. Now a second scenario has showed up to tip the other way, so I'm wondering if you mind a renaming/repurpose of the changes added in #38 or add generic container port, service, and ingress declarations alongside dynmap?

**Comment by billimek** [comment]
@itzg I agree that a generic approach would be useful to support something other than just `dynmap`.  Do you think it's likely that we would need to consider more than one of these extra things being used at a time?

Making it support n-number of additional sidecars/services/ingresses introduces a lot more complexity IMO.

Perhaps we look to make what we have use a more generic name (as you suggest above) and wait to consider supporting _multiple concurrent_ sidecars until they are needed?

**Comment by anthr76** [comment]
For what it's worth, and to @billimek point bluemap is supporting running it outside of your game server i.e `server/plugins` like in a sidecar though the quality isn't as great yet (can't see live players last I checked).

https://github.com/BlueMap-Minecraft/BlueMap/wiki/Directly-hosting-BlueMap-with-external-webservers

**Comment by ChipWolf** [comment]
> For what it's worth, and to @billimek 's point bluemap is supporting running it outside of your game server i.e not `server/plugins` like in a sidecar though the quality isn't as great yet (can't see live players last I checked). Also doesn't have a container yet
> 
> https://github.com/BlueMap-Minecraft/BlueMap/wiki/Installation#on-the-cli--standalone

I think building a container for Bluemap would be out of the scope of this project, but I'm sure a feature request could be opened to support it once it exists

**Comment by anthr76** [comment]
I agree. Just a generic service in the chart here would suffice.
