### ISSUE TITLE
No Auto Pause in Helm Chart

### ISSUE THREAD

**Issue by masterpuck** [itzg/minecraft-server-charts#64]
The helm chart does not have any ENABLE_AUTOPAUSE option though the base image supports it. Am I missing something?

**Comment by itzg** [comment]
You're correct, it's not there. I hesitate to add it since I'm not confident it will perform well consistently. I often find kubernetes containers (kubelet, etcd, kube-controller-manager) processes using much more CPU than an idle minecraft container.

**Comment by masterpuck** [comment]
its sitting at about .3 cpu and 2.5gigs of ram idle. It was really the ram usage I was looking to drop. Thank you for the update

**Comment by itzg** [comment]
Ah, if reduced ram usage was a goal, then the paused container/process still holds the memory when it is paused.
