### ISSUE TITLE
minecraft-proxy 2.0.2 does not exist in Helm Repo

### ISSUE THREAD

**Issue by mintaka-orionis** [itzg/minecraft-server-charts#70]
The version of minecraft-proxy in Helm Repo is only up to 2.0.1.

**Comment by itzg** [comment]
I bumped the version to 2.0.3 to force a re-release.

This was the build that was supposed to release 2.0.2, but it thought there weren't changes

https://github.com/itzg/minecraft-server-charts/runs/2287164022?check_suite_focus=true

**Comment by mintaka-orionis** [comment]
I was able to update the chart version to 2.0.3.
Thank you very much.
