### ISSUE TITLE
Feature Request(/Contribution Offer): Scripts to support easy use of this chart

### ISSUE THREAD

**Issue by gilesknap** [itzg/minecraft-server-charts#73]
Thanks so much, this is a really useful project, It has transformed the ease of management of (java) Minecraft servers for me.

However, quite a bit of background in K8S and Helm is required to take advantage of it. I propose that a the project provides a script for a simple CLI for deploying and managing servers. 

I have a fully functional project which I'm happy to contribute here if you think appropriate. See the last section of the README for details of my CLI script. (I also include simple instructions for getting a cluster up and running at home)

https://github.com/gilesknap/k3s-minecraft

**Comment by itzg** [comment]
I agree, the learning curve gets pretty steep with Kubernetes + Helm. I like the content I'm seeing in your repo and would propose adding a "Tutorials" section to this chart repo that would link to your repo. Would that work for you?

**Comment by itzg** [comment]
If you want, you can PR that section into the README.

**Comment by gilesknap** [comment]
Will do.

**Comment by vorburger** [comment]
Close this, given it's now there on https://github.com/itzg/minecraft-server-charts/tree/master/charts/minecraft#tutorials ?

**Comment by itzg** [comment]
Thanks for the reminder @vorburger
