### ISSUE TITLE
Add a set of backup flag to enable itzg/mc-backup sidecar

### ISSUE THREAD

**Issue by displague** [itzg/minecraft-server-charts#91]
https://hub.docker.com/r/itzg/mc-backup offers instructions on how to configure mc-backup within Kubernetes.

Since this is the official home of the itzg minecraft chart, it would benefit users to have this backup option integrated and configurable via helm chart flags.

**Comment by merkinbob** [comment]
see #93, i didn't add rclone or restic completely yet, i have tested this on my server, and seems to be ok.  was able to successfully backup and restore

**Comment by merkinbob** [comment]
@displague  this has been merged

**Comment by itzg** [comment]
I had forgotten to link up this issue, so I'll close it out.
